---
title: "Orthogonal validation of cell lineage assignment with signatures from Hay et al (Human Cell Atlas)"
author: "chiara caprioli"
date: "27/07/2022"
output: html_document
---

```{r, message = FALSE}
library(Seurat)
library(tidyverse)
library(ggridges)
library(msigdbr)
```

```{r}
colors <- list()

colors$sample <- setNames(
  c("#227093", "#ffb142", "#485460"),
  c("AML4", "AML5", "sAML1")
)

colors$cell_cycle <- setNames(
  c("#45aaf2", "#f1c40f", "#e74c3c"),
  c("G1", "S", "G2M")
)

colors$cell_type <- setNames(
  colors$cell_type <- c(
  "#FEA47F","#25CCF7","#EAB543","#55E6C1","#CAD3C8",
  "#F97F51","#1B9CFC","#F8EFBA","#58B19F","#2C3A47",
  "#B33771","#3B3B98","#FD7272","#9AECDB","#D6A2E8",
  "#6D214F","#182C61","#FC427B","#BDC581","#82589F",
  "#EE5A24","#009432", "#F79F1F", "#A3CB38", "#1289A7",
  "#D980FA", "#B53471"), 
c("HSC", "LMPP", "GMP", "Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono", "CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2", "Prog_B 1", "Prog_B 2", "Naive B", "Memory B", "Plasmablast"))

colors$aggregated_lineage <- setNames(
  c('#D69C4EFF','#C93312FF', '#174D79FF', '#CADDE1FF', 'lightgrey'),
  c('HSC_progenitors', 'myeloid', 'T_NK', 'B', 'unclassified')
)


BWR <- colorRampPalette(c("#053061", "#2166AC","#4393C3", "#92C5DE", 
                           "#D1E5F0", "#FFFFFF", "#FDDBC7", "#F4A582", 
                           "#D6604D", "#B2182B","#67001F"))
```

```{r}
AML.combined.sct <- readRDS('/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML.combined.sct.rds')
AML4 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML4.rds")
AML5 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML5.rds")
sAML1 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/sAML1.rds")
HCA_BM <- readRDS("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/HCA_BM/hcabm40k_l2.sct.rds")
```

### Expression of gene sets of interest
#### Download gene sets
```{r}
HAY_BONE_MARROW_CD34_POS_CLP <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_CLP') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_CLP <- HAY_BONE_MARROW_CD34_POS_CLP[which(HAY_BONE_MARROW_CD34_POS_CLP %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_EO_B_MAST <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_EO_B_MAST') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_EO_B_MAST <- HAY_BONE_MARROW_CD34_POS_EO_B_MAST[which(HAY_BONE_MARROW_CD34_POS_EO_B_MAST %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_ERP <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_ERP') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_ERP <- HAY_BONE_MARROW_CD34_POS_ERP[which(HAY_BONE_MARROW_CD34_POS_ERP %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_ERP_EARLY <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_ERP_EARLY') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_ERP_EARLY <- HAY_BONE_MARROW_CD34_POS_ERP_EARLY[which(HAY_BONE_MARROW_CD34_POS_ERP_EARLY %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_GRAN <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_GRAN') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_GRAN <- HAY_BONE_MARROW_CD34_POS_GRAN[which(HAY_BONE_MARROW_CD34_POS_GRAN %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_HSC <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_HSC') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_HSC <- HAY_BONE_MARROW_CD34_POS_HSC[which(HAY_BONE_MARROW_CD34_POS_HSC %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_LMPP <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_LMPP') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_LMPP <- HAY_BONE_MARROW_CD34_POS_LMPP[which(HAY_BONE_MARROW_CD34_POS_LMPP %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK <- HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK[which(HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_MEP <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_MEP') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_MEP <- HAY_BONE_MARROW_CD34_POS_MEP[which(HAY_BONE_MARROW_CD34_POS_MEP %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_MKP <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_MKP') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_MKP <- HAY_BONE_MARROW_CD34_POS_MKP[which(HAY_BONE_MARROW_CD34_POS_MKP %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_MULTILIN <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_MULTILIN') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_MULTILIN <- HAY_BONE_MARROW_CD34_POS_MULTILIN[which(HAY_BONE_MARROW_CD34_POS_MULTILIN %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_PRE_B <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_PRE_B') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_PRE_B <- HAY_BONE_MARROW_CD34_POS_PRE_B[which(HAY_BONE_MARROW_CD34_POS_PRE_B %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD34_POS_PRE_PC <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD34_POS_PRE_PC') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD34_POS_PRE_PC <- HAY_BONE_MARROW_CD34_POS_PRE_PC[which(HAY_BONE_MARROW_CD34_POS_PRE_PC %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_CD8_T_CELL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_CD8_T_CELL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_CD8_T_CELL <- HAY_BONE_MARROW_CD8_T_CELL[which(HAY_BONE_MARROW_CD8_T_CELL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_DENDRITIC_CELL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_DENDRITIC_CELL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_DENDRITIC_CELL <- HAY_BONE_MARROW_DENDRITIC_CELL[which(HAY_BONE_MARROW_DENDRITIC_CELL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_EARLY_ERYTHROBLAST <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_EARLY_ERYTHROBLAST') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_EARLY_ERYTHROBLAST <- HAY_BONE_MARROW_EARLY_ERYTHROBLAST[which(HAY_BONE_MARROW_EARLY_ERYTHROBLAST %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_EOSINOPHIL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_EOSINOPHIL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_EOSINOPHIL <- HAY_BONE_MARROW_EOSINOPHIL[which(HAY_BONE_MARROW_EOSINOPHIL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_ERYTHROBLAST <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_ERYTHROBLAST') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_ERYTHROBLAST <- HAY_BONE_MARROW_ERYTHROBLAST[which(HAY_BONE_MARROW_ERYTHROBLAST %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_FOLLICULAR_B_CELL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_FOLLICULAR_B_CELL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_FOLLICULAR_B_CELL <- HAY_BONE_MARROW_FOLLICULAR_B_CELL[which(HAY_BONE_MARROW_FOLLICULAR_B_CELL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_IMMATURE_NEUTROPHIL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_IMMATURE_NEUTROPHIL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_IMMATURE_NEUTROPHIL <- HAY_BONE_MARROW_IMMATURE_NEUTROPHIL[which(HAY_BONE_MARROW_IMMATURE_NEUTROPHIL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_MONOCYTE <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_MONOCYTE') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_MONOCYTE <- HAY_BONE_MARROW_MONOCYTE[which(HAY_BONE_MARROW_MONOCYTE %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_NAIVE_T_CELL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_NAIVE_T_CELL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_NAIVE_T_CELL <- HAY_BONE_MARROW_NAIVE_T_CELL[which(HAY_BONE_MARROW_NAIVE_T_CELL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_NEUTROPHIL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_NEUTROPHIL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_NEUTROPHIL <- HAY_BONE_MARROW_NEUTROPHIL[which(HAY_BONE_MARROW_NEUTROPHIL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_NK_CELLS <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_NK_CELLS') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_NK_CELLS <- HAY_BONE_MARROW_NK_CELLS[which(HAY_BONE_MARROW_NK_CELLS %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_PLASMA_CELL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_PLASMA_CELL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_PLASMA_CELL <- HAY_BONE_MARROW_PLASMA_CELL[which(HAY_BONE_MARROW_PLASMA_CELL %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_PLATELET <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_PLATELET') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_PLATELET <- HAY_BONE_MARROW_PLATELET[which(HAY_BONE_MARROW_PLATELET %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_PRE_DENDRITIC <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_PRE_DENDRITIC') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_PRE_DENDRITIC <- HAY_BONE_MARROW_PRE_DENDRITIC[which(HAY_BONE_MARROW_PRE_DENDRITIC %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_PRO_B <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_PRO_B') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_PRO_B <- HAY_BONE_MARROW_PRO_B[which(HAY_BONE_MARROW_PRO_B %in% rownames(AML.combined.sct@assays$SCT@data))]

HAY_BONE_MARROW_STROMAL <- msigdbr(species = 'Homo sapiens', category = 'C8') %>%
  filter(gs_name == 'HAY_BONE_MARROW_STROMAL') %>%
  pull(gene_symbol) %>%
  unique()
HAY_BONE_MARROW_STROMAL <- HAY_BONE_MARROW_STROMAL[which(HAY_BONE_MARROW_STROMAL %in% rownames(AML.combined.sct@assays$SCT@data))]
```

```{r}
list_HAY_genes <- list(HAY_BONE_MARROW_CD34_POS_HSC, 
                HAY_BONE_MARROW_CD34_POS_LMPP, 
                HAY_BONE_MARROW_CD34_POS_MULTILIN,
                HAY_BONE_MARROW_CD34_POS_MEP,
                HAY_BONE_MARROW_CD34_POS_ERP,
                HAY_BONE_MARROW_CD34_POS_ERP_EARLY,
                HAY_BONE_MARROW_CD34_POS_MKP,
                HAY_BONE_MARROW_CD34_POS_CLP, 
                HAY_BONE_MARROW_CD34_POS_EO_B_MAST,
                HAY_BONE_MARROW_CD34_POS_GRAN,
                HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK,
                HAY_BONE_MARROW_CD34_POS_PRE_B, 
                HAY_BONE_MARROW_CD34_POS_PRE_PC, 
                HAY_BONE_MARROW_IMMATURE_NEUTROPHIL,
                HAY_BONE_MARROW_NEUTROPHIL, 
                HAY_BONE_MARROW_EOSINOPHIL, 
                HAY_BONE_MARROW_MONOCYTE, 
                HAY_BONE_MARROW_PRE_DENDRITIC,              
                HAY_BONE_MARROW_DENDRITIC_CELL, 
                HAY_BONE_MARROW_EARLY_ERYTHROBLAST, 
                HAY_BONE_MARROW_ERYTHROBLAST, 
                HAY_BONE_MARROW_PLATELET,
                HAY_BONE_MARROW_NAIVE_T_CELL, 
                HAY_BONE_MARROW_CD8_T_CELL, 
                HAY_BONE_MARROW_NK_CELLS,
                HAY_BONE_MARROW_PRO_B,
                HAY_BONE_MARROW_FOLLICULAR_B_CELL,
                HAY_BONE_MARROW_PLASMA_CELL,
                HAY_BONE_MARROW_STROMAL)

names(list_HAY_genes) <- list('HAY_BONE_MARROW_CD34_POS_HSC', 
                'HAY_BONE_MARROW_CD34_POS_LMPP', 
                'HAY_BONE_MARROW_CD34_POS_MULTILIN',
                'HAY_BONE_MARROW_CD34_POS_MEP',
                'HAY_BONE_MARROW_CD34_POS_ERP',
                'HAY_BONE_MARROW_CD34_POS_ERP_EARLY',
                'HAY_BONE_MARROW_CD34_POS_MKP',
                'HAY_BONE_MARROW_CD34_POS_CLP', 
                'HAY_BONE_MARROW_CD34_POS_EO_B_MAST',
                'HAY_BONE_MARROW_CD34_POS_GRAN',
                'HAY_BONE_MARROW_CD34_POS_LYMPHOID_UNK',
                'HAY_BONE_MARROW_CD34_POS_PRE_B', 
                'HAY_BONE_MARROW_CD34_POS_PRE_PC', 
                'HAY_BONE_MARROW_IMMATURE_NEUTROPHIL',
                'HAY_BONE_MARROW_NEUTROPHIL', 
                'HAY_BONE_MARROW_EOSINOPHIL', 
                'HAY_BONE_MARROW_MONOCYTE', 
                'HAY_BONE_MARROW_PRE_DENDRITIC',              
                'HAY_BONE_MARROW_DENDRITIC_CELL', 
                'HAY_BONE_MARROW_EARLY_ERYTHROBLAST', 
                'HAY_BONE_MARROW_ERYTHROBLAST', 
                'HAY_BONE_MARROW_PLATELET',
                'HAY_BONE_MARROW_NAIVE_T_CELL', 
                'HAY_BONE_MARROW_CD8_T_CELL', 
                'HAY_BONE_MARROW_NK_CELLS',
                'HAY_BONE_MARROW_PRO_B',
                'HAY_BONE_MARROW_FOLLICULAR_B_CELL',
                'HAY_BONE_MARROW_PLASMA_CELL',
                'HAY_BONE_MARROW_STROMAL')

saveRDS(list_HAY_genes, 'list_HAY_genes.rds')
```

#### Mean expression of lineage-specific Hay signatures
```{r}
for (i in names(list_genes)){
  tibble <- tibble(
  sample = AML.combined.sct@meta.data$sample,
  cell_type = AML.combined.sct@meta.data$refined_lineage,
  mean_expression = Matrix::colMeans(AML.combined.sct@assays$SCT@data[list_genes[[i]],])
  )
  p = ggplot(tibble, aes(x = mean_expression, y = cell_type, fill = cell_type)) +
    #geom_density_ridges(rel_min_height = 0.005) +
    stat_density_ridges(quantile_lines = TRUE, quantiles = 2, 
                        color = "black", rel_min_height = 0.005, scale = 0.9) +
    scale_fill_manual(values = colors$cell_type.2) +
    theme_bw() +
    labs(title = i, x = 'Mean expression') +
    scale_y_discrete(limits=rev) +
    facet_wrap(~sample) +
    theme(
      plot.title = element_text(size = 13),
      axis.text.y = element_text(size = 11, color = 'black'),
      axis.text.x = element_text(size = 11, color = 'black'),
      axis.title.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      legend.position = 'none',
      strip.text = element_text(face = 'bold')) 
     
    
  ggsave(paste0('./', i,'_mean_exp.png'), p, height = 12, width = 7)
}
```

Alternatively
```{r}
temp_labels <- AML.combined.sct@meta.data %>%
  group_by(refined_lineage) %>%
  tally() %>%
  dplyr::rename('cell_type' = refined_lineage)

# violin
for (i in names(list_genes)){
  tibble = tibble(
    cell_type = AML.combined.sct@meta.data$refined_lineage,
    mean_expression = Matrix::colMeans(AML.combined.sct@assays$SCT@data[list_genes[[i]],])
    )
  p = ggplot(tibble, aes(x = cell_type, y = mean_expression, fill = cell_type)) +
    geom_violin(draw_quantiles = c(0.5), scale = 'width', trim = F, size = 0.2) +
    geom_text(
      data = temp_labels,
      aes(
        x = cell_type,
        y = -Inf,
        label = paste0('n = ', format(n, big.mark = ',', trim = TRUE)),
        vjust = -1), 
    color = 'black', size = 1.5) +
    theme_bw() +
    scale_fill_manual(values = colors$cell_type.2) +
    scale_x_discrete() +
    scale_y_continuous(name = 'Mean log expression', labels = scales::comma, expand = c(0.05, 0)) +
    labs(title = i) +
    theme(
      plot.title = element_text(size = 10),
      axis.text.y = element_text(size = 5, color = 'black'),
      axis.title.y = element_text(size = 7),
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 6.5, color = 'black'),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      legend.position = 'none'
      )
  ggsave(paste0('./', i,'_mean_exp.png'), p, height = 2, width = 8)
}

#box
for (i in names(list_genes)){
  tibble = tibble(
    cell_type = AML.combined.sct@meta.data$refined_lineage,
    mean_expression = Matrix::colMeans(AML.combined.sct@assays$SCT@data[list_genes[[i]],])
    )
  p = ggplot(tibble, aes(x = cell_type, y = mean_expression, fill = cell_type)) +
    geom_boxplot(size = 0.2, outlier.fill = NULL, outlier.size = 0.5) +
    geom_text(
      data = temp_labels,
      aes(
        x = cell_type,
        y = -Inf,
        label = paste0('n = ', format(n, big.mark = ',', trim = TRUE)),
        vjust = -1), 
    color = 'black', size = 1.5) +
    theme_bw() +
    scale_fill_manual(values = colors$cell_type.2) +
    scale_x_discrete() +
    scale_y_continuous(name = 'Mean log expression', labels = scales::comma, expand = c(0.05, 0)) +
    labs(title = i) +
    theme(
      plot.title = element_text(size = 10),
      axis.text.y = element_text(size = 5, color = 'black'),
      axis.title.y = element_text(size = 7),
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 6.5, color = 'black'),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      legend.position = 'none'
      )
  ggsave(paste0('./', i,'_mean_exp_box.png'), p, height = 2, width = 8)
}
```

## Lineage validation on each sample individually
```{r}
list_HAY_genes <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/cell_lineage_validation/list_HAY_genes.rds")

AML_BM.sct <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML_BM.sct.rds")
```

```{r}
# check n genes per signature to set ctrl parameter in AddModuleScore
geneSets <- list_HAY_genes

df <- data.frame()
for (i in names(geneSets)) {
  x = data.frame(
    signature = i,
    genes_in_signature = length(geneSets[[i]])
)
  df = rbind(x, df)
} 

df
```

```{r}
AML_BM.sct <- AddModuleScore(
  AML_BM.sct,
  features = list_HAY_genes,
  pool = NULL,
  nbin = 10,
  ctrl = 1000,
  k = FALSE,
  assay = 'SCT',
  name = names(list_HAY_genes),
  seed = 1,
  search = FALSE
)
```

```{r}
sig <- colnames(AML_BM.sct@meta.data)[grep('HAY', colnames(AML_BM.sct@meta.data))]  
```

```{r}
for (i in sig) {
  AML_BM.sct@meta.data[i] <- 
    AML_BM.sct@meta.data %>% 
    pull(i) %>% 
    scales::rescale(0:1)
  
  p = FeaturePlot(AML_BM.sct, 
            features = i,
            split.by = 'sample',
            keep.scale = NULL, 
            order = TRUE, 
            pt.size = 0.1,
            combine = T) &
  scale_colour_gradientn(
    limits = c(0,1),
    n.breaks = 6,
    colours = rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))) &
  theme_bw() &
  theme(panel.grid = element_blank())
  
  ggsave(paste0(i, '_split.png'), p +
           patchwork::plot_layout(ncol = 4, heights = 5, widths = 5.5) +
           patchwork::plot_annotation(title = i, 
                                      theme = theme(
                                        plot.title = element_text(
                                          face = 'bold', 
                                          hjust = 0.5,
                                          vjust = 1,
                                          size = 15))),
         height = 5, width = 23)

}
```

## LSC score
```{r}
# LSC17: Ng 2016, Ext Data Table 1 (List of 104 DEG, fold change LSC+ vs LSC-)

LSC17 <- c('CD34', 'LAPTM4B', 'ARHGAP22', 'SMIM24', 'KIAA0125', 
           'MMRN1', 'DNMT3B', 'SOCS2', 'CDK6', 'NGFRAP1', 'CPXM1', 
           'ZBTB46', 'DPYSL3', 'NYNRIN', 'ADGRG1', 'AKR1C3', 'EMP1')
```

```{r}
AML_BM.sct <- AddModuleScore(
  AML_BM.sct,
  features = list(LSC17),
  pool = NULL,
  nbin = 10,
  ctrl = 1000,
  k = FALSE,
  assay = 'SCT',
  name = 'LSC_Ng',
  seed = 1,
  search = FALSE
)
```

```{r}
saveRDS(AML_BM.sct, "/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML_BM.sct.rds")
```

```{r}
AML_BM.sct@meta.data$LSC_Ng1 <- 
  AML_BM.sct@meta.data %>% 
  pull(LSC_Ng1) %>% 
  scales::rescale(0:1)

p = FeaturePlot(AML_BM.sct, 
            features = 'LSC_Ng1',
            split.by = 'sample',
            keep.scale = NULL, 
            order = TRUE, 
            pt.size = 0.1,
            combine = T) &
  scale_colour_gradientn(
    limits = c(0,1),
    n.breaks = 6,
    colours = rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))) &
  theme_bw() &
  theme(panel.grid = element_blank())
  
ggsave('LSC17_split.png', p +
         patchwork::plot_layout(ncol = 4, heights = 5, widths = 5.5) +
         patchwork::plot_annotation(title = 'LSC17_Ng', 
                                    theme = theme(
                                      plot.title = element_text(
                                      face = 'bold', 
                                      hjust = 0.5,
                                      vjust = 1,
                                      size = 15))),
         height = 5, width = 23)
```

```{r}
genes <- LSC17$LSC17[which(LSC17$LSC17 %in% rownames(AML_BM.sct@assays$RNA@data))]

tib = tibble(
    cell_type = AML_BM.sct@meta.data$LSC17_AUC_class,
    mean_expression = Matrix::colMeans(AML_BM.sct@assays$RNA@data[genes,])
    )

  ggplot(tib, aes(x = cell_type, y = mean_expression, fill = cell_type)) +
        geom_violin(width = 0.7, scale = 'width', trim = F) +
        geom_boxplot(width=0.05, color = 'white', outlier.shape = NA) +
        theme_bw() +
        scale_x_discrete() +
    scale_fill_manual(values = c('darkred', 'lightgrey')) +
        scale_y_continuous(name = 'Log-normalized expression', labels = scales::comma, expand = c(0.08, 0)) +
        theme(
          axis.title.x = element_blank(),
          axis.text.x = element_text(color = 'black', size = 11),
          axis.title.y = element_text(color = 'black', size = 12),
          axis.text.y = element_text(color = 'black'),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          plot.title = element_text(face = 'bold'),
          legend.position = 'none'
          )
```


```{r}
ggsave('/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/plots/LSC17_expression_AUC_validated.png', height = 4, width = 5)
 
```

############ 3 AMLs
```{r}
AML.combined.sct <- AddModuleScore(
  AML.combined.sct,
  features = list(LSC17),
  pool = NULL,
  nbin = 10,
  ctrl = 1000,
  k = FALSE,
  assay = 'SCT',
  name = 'LSC_Ng',
  seed = 1,
  search = FALSE
)

AML.combined.sct@meta.data$LSC_Ng1 <- 
  AML.combined.sct@meta.data %>% 
  pull(LSC_Ng1) %>% 
  scales::rescale(0:1)

p = FeaturePlot(AML.combined.sct, 
            features = 'LSC_Ng1',
            split.by = 'sample',
            keep.scale = NULL, 
            order = TRUE, 
            pt.size = 0.1,
            combine = T) &
  scale_colour_gradientn(
    limits = c(0,1),
    n.breaks = 6,
    colours = rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))) &
  theme_bw() &
  theme(panel.grid = element_blank())
  
ggsave('AML_integrated_LSC17_split.png', p +
         patchwork::plot_layout(ncol = 3, heights = 5, widths = 5.5) +
         patchwork::plot_annotation(title = 'LSC17_Ng', 
                                    theme = theme(
                                      plot.title = element_text(
                                      face = 'bold', 
                                      hjust = 0.5,
                                      vjust = 1,
                                      size = 15))),
         height = 5, width = 18)


```

```{r}
library(AUCell)

LSC17 <- list(LSC17)
names(LSC17) <- 'LSC17'
```

```{r}
subset_seurat <- AML.combined.sct[,which(AML.combined.sct$sample == 'sAML1')]
exprMatrix <- GetAssayData(subset_seurat, assay = 'SCT', slot = 'data')

# Calculate enrichment scores
cells_AUC <- AUCell_run(exprMatrix, LSC17, featureType = "genes",
                        normAUC = TRUE, aucMaxRank = ceiling(0.45 * nrow(exprMatrix)))
#save(cells_AUC, file="sAML1_lineage_AUC.RData")
```

```{r}
# explore thresholds automatically set

cells_assignment <- AUCell_exploreThresholds(cells_AUC, plotHist=TRUE, assign=TRUE) 
#The distributions are plotted as dotted lines over the histogram and the corresponding thresholds as vertical bars in the matching color. The thicker vertical line indicates the threshold selected by default ($aucThr$selected): the highest value to reduce the false positives.
```

```{r}
UMAP <- bind_cols(subset_seurat@meta.data, 
                  as.data.frame(subset_seurat@reductions$UMAP@cell.embeddings)) %>% 
  dplyr::select(UMAP_1, UMAP_2)
```

```{r}
selectedThresholds <- getThresholdSelected(cells_assignment) 

for(geneSetName in names(selectedThresholds)) {
  colorPal_Neg <- 'lightgrey'
  colorPal_Pos <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(9, 'Reds'))(9)
  # Split cells according to their AUC value for the gene set
  passThreshold <- getAUC(cells_AUC)[geneSetName,] > selectedThresholds[geneSetName] 
  if(sum(passThreshold) >0 ) {
    aucSplit <- split(getAUC(cells_AUC)[geneSetName,], passThreshold)
    # Assign cell color
    cellColor <- c(setNames(colorPal_Neg[cut(aucSplit[[1]], breaks=9)], names(aucSplit[[1]])),
    setNames(colorPal_Pos[cut(aucSplit[[2]], breaks=9)], names(aucSplit[[2]])))
    # Plot
    plot(UMAP, main='LSC17',
    col=cellColor[rownames(UMAP)], pch=16, cex = 0.3)
  } 
  }
```

```{r}
# manual checking

pdf('sAML1_LSC17_AUC_manual_hist.pdf', height = 4, width = 5)

AUCell_plotHist(cells_AUC[1,], aucThr=0.43)
abline(v=0.43, col = 'orange', lty = 2, lwd = 2)

dev.off()
```

```{r}
selectedThresholds <- 0.43

colorPal_Neg <- 'lightgrey'
colorPal_Pos <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(9, 'Reds'))(9)

# Split cells according to their AUC value for the gene set
passThreshold <- getAUC(cells_AUC)[geneSetName,] > selectedThresholds
aucSplit <- split(getAUC(cells_AUC)[geneSetName,], passThreshold)
cellColor <- c(setNames(colorPal_Neg[cut(aucSplit[[1]], breaks=9)], names(aucSplit[[1]])),
setNames(colorPal_Pos[cut(aucSplit[[2]], breaks=9)], names(aucSplit[[2]])))
```

```{r}
pdf('sAML1_LSC17_AUC_manual_UMAP.pdf', height = 5, width = 5)

plot(UMAP, main='sAML1',
    col=cellColor[rownames(UMAP)], pch=16, cex = 0.2)
legend('bottomright', legend=c("AUC < threshold", "AUC > threshold"),
       fill=c(colorPal_Neg, 'red'))

dev.off()
```

```{r}
sAML1_newSelectedCells <- names(which(getAUC(cells_AUC)[1,]>0.43))
length(sAML1_newSelectedCells)
```

```{r}
newSelectedCells <- c(AML4_newSelectedCells, AML5_newSelectedCells, sAML1_newSelectedCells)

AML.combined.sct$'LSC17_AUC_class' <- ifelse(colnames(AML.combined.sct) %in% newSelectedCells, 'LSC', 'no_LSC')
AML.combined.sct$LSC17_AUC_class <- factor(AML.combined.sct$LSC17_AUC_class, levels = c('LSC', 'no_LSC'))

saveRDS(AML.combined.sct, "/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML.combined.sct.rds")
```

```{r}
genes <- LSC17$LSC17[which(LSC17$LSC17 %in% rownames(AML.combined.sct@assays$RNA@data))]

tib = tibble(
    cell_type = AML.combined.sct@meta.data$LSC17_AUC_class,
    mean_expression = Matrix::colMeans(AML.combined.sct@assays$RNA@data[genes,])
    )

  ggplot(tib, aes(x = cell_type, y = mean_expression, fill = cell_type)) +
        geom_violin(width = 0.7, scale = 'width', trim = F) +
        geom_boxplot(width=0.05, color = 'white', outlier.shape = NA) +
        theme_bw() +
        scale_x_discrete() +
    ggtitle('All cells') +
    scale_fill_manual(values = c('darkred', 'lightgrey')) +
        scale_y_continuous(name = 'Log-normalized expression', labels = scales::comma, expand = c(0.08, 0)) +
        theme(
          axis.title.x = element_blank(),
          axis.text.x = element_text(color = 'black', size = 11),
          axis.title.y = element_text(color = 'black', size = 12),
          axis.text.y = element_text(color = 'black'),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          plot.title = element_text(face = 'bold', hjust = 0.5),
          legend.position = 'none'
          )
  
ggsave('/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/plots/LSC17_expression_AUC_validated.png', height = 4, width = 5)
 
```

```{r}
subset <- AML.combined.sct[,which(AML.combined.sct$aggregated_lineage == 'HSC_progenitors')]
genes <- LSC17$LSC17[which(LSC17$LSC17 %in% rownames(subset@assays$RNA@data))]

tib = tibble(
    cell_type = subset@meta.data$LSC17_AUC_class,
    mean_expression = Matrix::colMeans(subset@assays$RNA@data[genes,])
    )

  ggplot(tib, aes(x = cell_type, y = mean_expression, fill = cell_type)) +
        geom_violin(width = 0.7, scale = 'width', trim = F) +
        geom_boxplot(width=0.05, color = 'white', outlier.shape = NA) +
        theme_bw() +
        ggtitle('HSC_progenitors') +
        scale_x_discrete() +
    scale_fill_manual(values = c('darkred', 'lightgrey')) +
        scale_y_continuous(name = 'Log-normalized expression', labels = scales::comma, expand = c(0.08, 0)) +
        theme(
          axis.title.x = element_blank(),
          axis.text.x = element_text(color = 'black', size = 11),
          axis.title.y = element_text(color = 'black', size = 12),
          axis.text.y = element_text(color = 'black'),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          plot.title = element_text(face = 'bold', hjust = 0.5),
          legend.position = 'none'
          )
  
ggsave('/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/plots/LSC17_expression_AUC_validated_HSC.png', height = 4, width = 5)
```

```{r}
sessionInfo()
```

