---
title: "integration"
author: "chiara caprioli"
date: "13/08/2022"
output: html_document
---

### Set up environment
```{r}
library(Seurat)
library(tidyverse)
library(viridis)
library(patchwork)
set.seed(123123)
```

```{r, setup, include=FALSE}
# set working directory
knitr::opts_knit$set(root.dir = '/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/integration/3_AML/')
```

```{r}
colors <- list()

colors$sample <- setNames(
  c("#227093", "#ffb142", "#485460"),
  c("AML4", "AML5", "sAML1")
)

colors$cell_cycle <- setNames(
  c("#45aaf2", "#f1c40f", "#e74c3c", "#7f8c8d"),
  c("G1", "S", "G2M", "-")
)

colors$cell_type <- setNames(
  colors$cell_type <- c(
  "#FEA47F","#25CCF7","#EAB543","#55E6C1","#CAD3C8",
  "#F97F51","#1B9CFC","#F8EFBA","#58B19F","#2C3A47",
  "#B33771","#3B3B98","#FD7272","#9AECDB","#D6A2E8",
  "#6D214F","#182C61","#FC427B","#BDC581","#82589F",
  "#EE5A24","#009432", "#F79F1F", "#A3CB38", "#1289A7",
  "#D980FA", "#B53471"), 
c("HSC", "LMPP", "GMP", "Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono", "CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2", "Prog_B 1", "Prog_B 2", "Naive B", "Memory B", "Plasmablast"))

colors$aggregated_lineage <- setNames(
  c('#D69C4EFF','#C93312FF', '#174D79FF', '#CADDE1FF'),
  c('HSC_progenitors', 'myeloid', 'T_NK', 'B')
)

BWR <- colorRampPalette(c("#053061", "#2166AC","#4393C3", "#92C5DE", 
                           "#D1E5F0", "#FFFFFF", "#FDDBC7", "#F4A582", 
                           "#D6604D", "#B2182B","#67001F"))
```

### Data integration Seurat v4 (Stuart, Cell 2019)
```{r}
# load objects
AML4 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML4.rds")
AML5 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML5.rds")
sAML1 <- readRDS("/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/sAML1.rds")

DefaultAssay(AML4) <- 'SCT'
DefaultAssay(AML5) <- 'SCT'
DefaultAssay(sAML1) <- 'SCT'
```

```{r}
AML_list <- list(AML4, AML5, sAML1)
var.features <- SelectIntegrationFeatures(object.list = AML_list, nfeatures = 3000)
AML_list <- PrepSCTIntegration(object.list = AML_list, anchor.features = var.features)
```

```{r}
anchors <- FindIntegrationAnchors(object.list = AML_list, normalization.method = "SCT", anchor.features = var.features)
AML.combined.sct <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
```

```{r}
library(scran)
library(scater)

sce <- as.SingleCellExperiment(AML.combined.sct, assay = 'RNA')
sce

plotHighestExprs(sce[,which(sce$sample == 'AML4')],
                 n = 50,
                 exprs_values = "counts",
                 colour_cells_by = 'sample') +
plotHighestExprs(sce[,which(sce$sample == 'AML5')],
                 n = 50,
                 exprs_values = "counts",
                 colour_cells_by = 'sample') +
plotHighestExprs(sce[,which(sce$sample == 'sAML1')],
                 n = 50,
                 exprs_values = "counts",
                 colour_cells_by = 'sample')
```

#### PCA
```{r, include=TRUE, warning=FALSE, message=FALSE, out.width="100%", fig.align="center"}
# Perform linear dimensional reduction on 50 PCs (default)
AML.combined.sct <- RunPCA(AML.combined.sct)
```

```{r}
DimPlot(AML.combined.sct, reduction = 'pca', group.by = 'sample', cols = colors$sample, pt.size = 0.6) +
  theme_bw() +
  labs(title = 'PCA by sample') +
  theme(panel.grid = element_blank())
```

### UMAP
```{r, include=TRUE, warning=TRUE, message=TRUE}
AML.combined.sct <- RunUMAP(
  AML.combined.sct,
  reduction.name = "UMAP",
  reduction = "pca",
  dims = 1:50
)
```

```{r}
dir.create('./plots/merged/integration')
knitr::opts_knit$set(root.dir = '/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration')
```

####sample
```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = sample)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$sample) +
  labs(color = "Sample") +
  guides(colour = guide_legend(override.aes = list(size = 2))) +
  theme(panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
    vjust = -1.5, hjust = 1.25, color = "black", size = 3.2
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_sample.png", height = 6, width = 7)
```

```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = sample)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$sample) +
  labs(color = "Sample") +
  guides(colour = guide_legend(override.aes = list(size = 2))) +
  theme(panel.grid = element_blank(),
        legend.position = 'none') +
  coord_fixed() +
  facet_wrap(~sample)

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_sample_split.png", height = 6, width = 17)
```

#### nCount, nFeature, percentMT
```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = nCount_SCT)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_viridis(
    guide = guide_colorbar(frame.colour = "black", ticks.colour = "black"),
    labels = scales::comma,
  ) +
  labs(color = "Number of\ntranscripts") +
  theme(legend.position = "right", panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
      vjust = -1.5, hjust = 1.25, color = "black", size = 2.5
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_nCount.png", height = 6, width = 7)
```

```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = nFeature_SCT)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_viridis(
    guide = guide_colorbar(frame.colour = "black", ticks.colour = "black"),
    labels = scales::comma,
  ) +
  labs(color = "Number of\nfeatures") +
  theme(legend.position = "right", panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
      vjust = -1.5, hjust = 1.25, color = "black", size = 2.5
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_nFeatures.png", height = 6, width = 7)
```

```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = percent_MT)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_viridis(
    guide = guide_colorbar(frame.colour = "black", ticks.colour = "black"),
    labels = scales::comma,
  ) +
  theme(legend.position = "right", panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
      vjust = -1.5, hjust = 1.25, color = "black", size = 2.5
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_percentMT.png", height = 6, width = 7)
```

#### cell cycle
```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = cell_cycle_seurat)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$cell_cycle) +
  labs(color = "cell cycle") +
  guides(colour = guide_legend(override.aes = list(size = 2))) +
  theme(panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
    vjust = -1.5, hjust = 1.25, color = "black", size = 3.2
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_cycle.png", height = 6, width = 7)
```

#### cell lineage 
```{r}
AML.combined.sct$cell_lineage <- factor(AML.combined.sct$cell_lineage, levels = c("HSC", "LMPP", "GMP", "Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono", "CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2", "Prog_B 1", "Prog_B 2", "Naive B", "Memory B", "Plasmablast"))
```

```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = cell_lineage)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$cell_type) +
  labs(color = "cell lineage") +
  guides(colour = guide_legend(override.aes = list(size = 2))) +
  theme(panel.grid = element_blank()) +
  coord_fixed() +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
    vjust = -1.5, hjust = 1.25, color = "black", size = 3.2
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage.png", height = 6, width = 8)
```

```{r}
bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = cell_lineage)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$cell_type) +
  labs(color = "cell lineage") +
  guides(colour = guide_legend(override.aes = list(size = 2))) +
  theme(panel.grid = element_blank()) +
  coord_fixed() +
  facet_wrap(~sample)

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage_split.png", height = 6, width = 18)
```

```{r}
UMAP_centers_cluster <- tibble(
  UMAP_1 = as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)$UMAP_1,
  UMAP_2 = as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)$UMAP_2,
  cell_lineage = AML.combined.sct@meta.data$cell_lineage
) %>%
  group_by(cell_lineage) %>%
  summarize(x = median(UMAP_1), y = median(UMAP_2))

bind_cols(AML.combined.sct@meta.data, as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = cell_lineage)) +
  geom_point(size = 0.2, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(values = colors$cell_type) +
  labs(color = "cell lineage") +
  coord_fixed() +
  geom_text(
    data = UMAP_centers_cluster,
    mapping = aes(x, y, label = cell_lineage),
    nudge_x = 0.4, nudge_y = 0.4,
    check_overlap = T,
    size = 3, color = 'black',
    show.legend = FALSE
  ) +
  annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim = TRUE)),
    vjust = -1.5, hjust = 1.25, color = "black", size = 2.5
  ) +
  theme(legend.position = "none", panel.grid = element_blank()) 

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage_labels.png", height = 6, width = 6)
```

Aggregate lineage
```{r}
HSC_progenitors <- c("HSC", "LMPP", "GMP", "Prog_B 1", "Prog_B 2")

myeloid <- c("Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono")
  
T_NK <- c("CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2")

B <- c("Naive B", "Memory B", "Plasmablast")
```

```{r}
AML.combined.sct$HSC_progenitors <- ifelse(AML.combined.sct$cell_lineage %in% HSC_progenitors, '1', '0')
AML.combined.sct$myeloid <- ifelse(AML.combined.sct$cell_lineage %in% myeloid, '1', '0')
AML.combined.sct$T_NK <- ifelse(AML.combined.sct$cell_lineage %in% T_NK, '1', '0')
AML.combined.sct$B <- ifelse(AML.combined.sct$cell_lineage %in% B, '1', '0')

AML.combined.sct$aggregated_lineage <- ifelse(AML.combined.sct$cell_lineage %in% HSC_progenitors, 'HSC_progenitors', ifelse(
  AML.combined.sct$cell_lineage %in% myeloid, 'myeloid', ifelse(
    AML.combined.sct$cell_lineage %in% T_NK, 'T_NK', ifelse(
      AML.combined.sct$cell_lineage %in% B, 'B', 'other'
    )
  )
))

AML.combined.sct$aggregated_lineage <- factor(AML.combined.sct$aggregated_lineage,
                                            levels = c('HSC_progenitors', 'myeloid', 'T_NK', 'B'))
```

```{r}
bind_cols(AML.combined.sct@meta.data,
          as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = aggregated_lineage)) +
  geom_point(size = 0.5, alpha = 0.8) +
  ggtitle('Cell lineage') +
  theme_bw() +
  scale_color_manual(name = 'Cell lineage', values = colors$aggregated_lineage) +
  theme(legend.position = "right", 
        panel.grid = element_blank()) +
  coord_fixed() +
    annotate(
    geom = "text", x = Inf, y = -Inf,
    label = paste0("n = ", format(nrow(AML.combined.sct@meta.data), big.mark = ",", trim =
                                    TRUE)),
    vjust = -1.5, hjust = 1.25, color = "black", size = 3.2
  )

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage_aggregated.png", height = 6, width = 7)
```

```{r}
bind_cols(AML.combined.sct@meta.data,
          as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = aggregated_lineage)) +
  geom_point(size = 0.5, alpha = 0.8) +
  theme_bw() +
  scale_color_manual(name = 'Cell lineage', values = colors$aggregated_lineage) +
  theme(legend.position = "right", 
        panel.grid = element_blank()) +
  coord_fixed() +
  facet_wrap(~sample)

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage_aggregated_split.png", height = 6, width = 18)
```

```{r}
bind_cols(AML.combined.sct@meta.data,
               as.data.frame(AML.combined.sct@reductions$UMAP@cell.embeddings)) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = predicted.celltype.score < 0.4)) +
  geom_point(size = 0.2) +
  theme_bw() +
  scale_color_manual(
    values = c('grey', 'blue'),
    guide = guide_legend(override.aes = list(size = 2)),
    name = 'Cell lineage prediction score',
    labels = c('≥ 0.4', '< 0.4')
  ) +
  theme(plot.title = element_text(face = "bold"), 
        panel.grid = element_blank()) +
  coord_fixed() +
  facet_wrap(~sample)

ggsave("/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/umap_cell_lineage_score_threshold.png", height = 6, width = 18)
```

```{r}
all_tab <- data.frame()

for (i in unique(AML.combined.sct@meta.data$sample)){
  x = AML.combined.sct@meta.data %>%
    filter(sample == i) %>%
    dplyr::select(cell_lineage, predicted.celltype.score) %>%
    pivot_wider(names_from = "cell_lineage", values_from = "predicted.celltype.score", 
             names_repair = "minimal", values_fn = mean) %>% unlist() %>% as.data.frame() %>%
    rownames_to_column('lineage') %>%
      mutate(sample = i)
    colnames(x)[2] <- 'mean_score'
  all_tab = rbind(all_tab, x)
}

all_tab <- all_tab %>%
      pivot_wider(names_from = "lineage", values_from = "mean_score") %>%
  column_to_rownames(var = 'sample')

all_tab <- all_tab[,match(levels(AML.combined.sct$cell_lineage), colnames(all_tab))] %>%
  as.matrix()

pheatmap::pheatmap(all_tab, 
         cluster_rows = F, cluster_cols = F,
         scale = "none", RColorBrewer::brewer.pal(n = 7, name = "Blues"),
         show_rownames = T, show_colnames = T, 
         legend = T, fontsize = 8.5, 
         angle_col = 45, na_col = 'lightgrey',
         cellwidth = 17, cellheight = 20,
         main = 'mean lineage prediction score',
         filename = "/hpcnfs/scratch/PGP/ccaprioli/working/SRSF2_3_AMLs/plots/merged/integration/mean_score_heatmap.png", height = 6, width = 10)
```

```{r}
saveRDS(AML.combined.sct, '/hpcnfs/scratch/PGP/SCMseq/short_read_analysis/data/AML.combined.sct.rds')
```

### Harmony
```{r}
library(harmony)
```

```{r}
list <- c(AML4, AML5, sAML1)

harm_AML <- merge(x = list[[1]], y = list[2:length(list)], merge.data=TRUE)

var.features <- SelectIntegrationFeatures(object.list = list, nfeatures = 3000)
VariableFeatures(harm_AML) <- var.features
```

#### PCA (needed for Harmony)
```{r, include=TRUE, warning=FALSE, message=FALSE, out.width="100%", fig.align="center"}
# Perform linear dimensional reduction on 50 PCs (default)
harm_AML <- RunPCA(harm_AML)
```

```{r}
DimPlot(harm_AML, reduction = 'pca', group.by = 'sample', cols = colors$sample, pt.size = 0.6) +
  theme_bw() +
  labs(title = 'PCA by sample') +
  theme(panel.grid = element_blank())
```

### Integration by Harmony
```{r}
harm_AML <- RunHarmony(
  harm_AML,
  group.by.vars = 'sample',
  reduction.name = "pca",
  assay.use = 'SCT',
  max.iter.harmony = 25,
  plot_convergence = T,
  verbose = T
)
```

```{r}
p1 <- DimPlot(harm_AML, reduction = "pca", pt.size = 0.1, group.by = "sample", cols = colors$sample) +
  theme_bw() +
  ggtitle('PCA') +
  theme(panel.grid = element_blank())
p2 <- DimPlot(harm_AML, reduction = "harmony", pt.size = 0.1, group.by = "sample", cols = colors$sample) +
  theme_bw() +
  ggtitle('Harmony') +
  theme(panel.grid = element_blank())

ggsave('./pca_harm_reduction.png', p1 + p2 + plot_layout(widths = 4, heights = 4, guides = 'collect'), width = 9, height = 4)
```

```{r}
harm_AML <- RunUMAP(
  harm_AML,
  reduction.name = "UMAP",
  reduction = "harmony",
  dims = 1:50,
  n.components = 2,
  seed.use = 100
)
```

```{r}
harm_AML$sample <- factor(harm_AML$sample, levels = c("AML4", "AML5", "sAML1"))
```

```{r}
harm_AML$cell_lineage <- factor(harm_AML$cell_lineage, levels = c("HSC", "LMPP", "GMP", "Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono", "CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2", "Prog_B 1", "Prog_B 2", "Naive B", "Memory B", "Plasmablast")) 

harm_AML$cell_lineage[which(harm_AML$sample == 'AML4')] <- AML.combined.sct$cell_lineage[which(AML.combined.sct$sample == 'AML4')]
harm_AML$cell_lineage[which(harm_AML$sample == 'AML5')] <- AML.combined.sct$cell_lineage[which(AML.combined.sct$sample == 'AML5')]
harm_AML$cell_lineage[which(harm_AML$sample == 'sAML1')] <- AML.combined.sct$cell_lineage[which(AML.combined.sct$sample == 'sAML1')]
```

```{r}
# Aggregate lineage
HSC_progenitors <- c("HSC", "LMPP", "GMP", "Prog_B 1", "Prog_B 2")

myeloid <- c("Prog_RBC", "Prog_Mk", "Prog_DC", "pDC", "cDC2", "CD14 Mono", "CD16 Mono")
  
T_NK <- c("CD4 Naive", "CD4 Memory" , "CD8 Naive",  "CD8 Effector_1", "CD8 Effector_2", "CD8 Memory_1", "Treg", "MAIT", "gdT",  "NK", "CD56 bright NK", "CD8 Memory_2")

B <- c("Naive B", "Memory B", "Plasmablast")

harm_AML$HSC_progenitors <- ifelse(harm_AML$cell_lineage %in% HSC_progenitors, '1', '0')
harm_AML$myeloid <- ifelse(harm_AML$cell_lineage %in% myeloid, '1', '0')
harm_AML$T_NK <- ifelse(harm_AML$cell_lineage %in% T_NK, '1', '0')
harm_AML$B <- ifelse(harm_AML$cell_lineage %in% B, '1', '0')

harm_AML$aggregated_lineage <- ifelse(harm_AML$cell_lineage %in% HSC_progenitors, 'HSC_progenitors', ifelse(
  harm_AML$cell_lineage %in% myeloid, 'myeloid', ifelse(
    harm_AML$cell_lineage %in% T_NK, 'T_NK', ifelse(
      harm_AML$cell_lineage %in% B, 'B', 'other'
    )
  )
))
harm_AML$aggregated_lineage <- factor(harm_AML$aggregated_lineage,
                                            levels = c('HSC_progenitors', 'myeloid', 'T_NK', 'B', 'other'))

length(which(harm_AML$aggregated_lineage == 'other'))
```

```{r}
saveRDS(harm_AML, './harm_AML.rds')
```

UMAP by sample
```{r}
DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "sample", 
        cols = colors$sample,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony.png',height = 5, width = 6.5)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "sample", 
        split.by = 'sample', 
        cols = colors$sample,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) + 
  NoLegend() 

ggsave('./AML.harmony_split.png',height = 5, width = 20)
```

UMAP by lineage
```{r}
DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_lineage", 
        cols = colors$cell_type,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony_lineage.png', height = 5, width = 8)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_lineage", 
        cols = colors$cell_type,
        label = T,
        label.size = 3,
        label.color = "black",
        label.box = F,
        repel = T,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank(),
        legend.position = 'none') 

ggsave('./AML.harmony_lineage_labels.png', height = 5, width = 5.5)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_lineage",
        split.by = 'sample',
        cols = colors$cell_type,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank(),
        legend.position = 'bottom') 

ggsave('./AML.harmony_lineage_split.png', height = 7, width = 20)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_lineage",
        split.by = 'sample',
        cols = colors$cell_type,
        label = T,
        label.size = 3,
        label.color = "black",
        label.box = F,
        repel = T,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank(),
        legend.position = 'none') 

ggsave('./AML.harmony_lineage_split_labels.png', height = 5, width = 20)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "aggregated_lineage", 
        cols = colors$aggregated_lineage,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony_aggr_lineage.png',height = 5, width = 6.5)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "aggregated_lineage", 
        split.by = 'sample',
        cols = colors$aggregated_lineage,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony_aggr_lineage_split.png',height = 5, width = 20)
```

UMAP by cell cycle
```{r}
DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_cycle_seurat", 
        split.by = 'sample', 
        cols = colors$cell_cycle,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony_cell_cycle_split.png',height = 5, width = 20)

DimPlot(harm_AML, 
        reduction = "UMAP", 
        group.by = "cell_cycle_seurat", 
        cols = colors$cell_cycle,
        pt.size = 0.2) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_blank()) 

ggsave('./AML.harmony_cell_cycle.png',height = 5, width = 5.7)
```

```{r}
sessionInfo()
```

